// <auto-generated />
using System;
using GerenciamentoDeFrota.Configs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciamentoDeFrota.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608193334_VeiculosCompleto")]
    partial class VeiculosCompleto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GerenciamentoDeFrota.Data.Models.AgendamentoManutencao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataAgendamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("HorarioAgendamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("KmAtualAgendamento")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<string>("Servico")
                        .HasColumnType("longtext");

                    b.Property<long>("VeiculoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId");

                    b.ToTable("AgendamentosManutencao");
                });

            modelBuilder.Entity("GerenciamentoDeFrota.Data.Models.CentrosCusto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool?>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CentrosCusto");
                });

            modelBuilder.Entity("GerenciamentoDeFrota.Data.Models.VeiculoAnexo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArquivo")
                        .HasColumnType("longtext");

                    b.Property<long>("VeiculoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId");

                    b.ToTable("VeiculosAnexos");
                });

            modelBuilder.Entity("GerenciamentoDeFrota.Data.Models.VeiculoDocumento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DtVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("VeiculoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId");

                    b.ToTable("VeiculosDocumentos");
                });

            modelBuilder.Entity("GerenciamentoDeFrota.Data.Models.Veiculos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int?>("AnoEmplacamento")
                        .HasColumnType("int");

                    b.Property<int?>("AnoFabricacao")
                        .HasColumnType("int");

                    b.Property<int?>("AnoModelo")
                        .HasColumnType("int");

                    b.Property<string>("Antt")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("AnttDtVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CNPJ")
                        .HasColumnType("longtext");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("CapacidadeCaixa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CapacidadePaletes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CapacidadeTanque")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Carroceria")
                        .HasColumnType("longtext");

                    b.Property<long?>("CentrosCustoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Cor")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CronoacografoDtVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataTacografo")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExtintorCodigo")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExtintorDtVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fabricante")
                        .HasColumnType("longtext");

                    b.Property<int?>("Ipva")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IpvaDtVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("KmAtual")
                        .HasColumnType("int");

                    b.Property<int>("KmHora")
                        .HasColumnType("int");

                    b.Property<int?>("Licenciamento")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LicenciamentoDtVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("LotacaoKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MesEmplacamento")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroFrota")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<string>("Padronizacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Placa")
                        .HasColumnType("longtext");

                    b.Property<string>("Proprietario")
                        .HasColumnType("longtext");

                    b.Property<string>("Renavam")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SeguroDtInicioVigencia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SeguroDtTerminoVigencia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SeguroNrApolice")
                        .HasColumnType("longtext");

                    b.Property<string>("SeguroSeguradora")
                        .HasColumnType("longtext");

                    b.Property<string>("SeguroTipo")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TaraKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Terceirizado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<string>("UF")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ValorFipe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("VeiculoTracao")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CentrosCustoId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("GerenciamentoDeFrota.Data.Models.AgendamentoManutencao", b =>
                {
                    b.HasOne("GerenciamentoDeFrota.Data.Models.Veiculos", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("GerenciamentoDeFrota.Data.Models.VeiculoAnexo", b =>
                {
                    b.HasOne("GerenciamentoDeFrota.Data.Models.Veiculos", "Veiculo")
                        .WithMany("Anexos")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("GerenciamentoDeFrota.Data.Models.VeiculoDocumento", b =>
                {
                    b.HasOne("GerenciamentoDeFrota.Data.Models.Veiculos", "Veiculo")
                        .WithMany("Documentos")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("GerenciamentoDeFrota.Data.Models.Veiculos", b =>
                {
                    b.HasOne("GerenciamentoDeFrota.Data.Models.CentrosCusto", "CentrosCusto")
                        .WithMany("Veiculos")
                        .HasForeignKey("CentrosCustoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CentrosCusto");
                });

            modelBuilder.Entity("GerenciamentoDeFrota.Data.Models.CentrosCusto", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("GerenciamentoDeFrota.Data.Models.Veiculos", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
